export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const UPDATE_MOVIES = 'UPDATE_MOVIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
